server:
  port: 8904


eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}


spring:
  datasource:
    driverClassName: ${rccp.micro.datasource.driverClassName}
    druid:
      main-db:
        url: ${rccp.micro.datasource.url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
      user-db:
        url: ${rccp.micro.datasource.user_url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
      search-db:
        url: ${rccp.micro.datasource.search_url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://${eureka.instance.hostname}:8767/

  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: ${rccp.micro.stream.kafka.binder.brokers}
          zk-nodes: ${rccp.micro.stream.kafka.binder.zk-nodes}
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1


management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  eureka:
    enabled: true



mybatis:
  mapper-locations: classpath:mapper/**/*.xml

debug: true
logging:
  level:
    com.zhuj.micro.service.**.*: debug
#七牛云相关
qnaccessKey: IgFqVYv0l245Skw1KPBje1PoAYaNUCoaXK4uM3ma
qnsecretKey: v5WQEaoHlTknZ8Z3K1saclHzETbX2ougyYGPRA_A
qnhubName: zhujianyun
RTMPpubUrl: pili-publish.zhujianyun.com
RTMPliveUrl: pili-live-rtmp.zhujianyun.com
HLSliveUrl: pili-live-hls.zhujianyun.com
HDLliveUrl: pili-live-hdl.zhujianyun.com
liveImageUrl: pili-snapshot.zhujianyun.com
#环信相关
GRANT_TYPE: client_credentials
HXCLIENT_ID: YXA6kI93vM02QaWtdCDYliUF_A
HXCLIENT_SECRET: YXA6wQNuk3pmpIr0ReGuussAXQaQSIc
HXAPP_NAME: zhujianyunprod
HXORG_NAME: 1137201013239659

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses: http://39.107.230.45:8000/xxl-job-admin
xxl.job.accessToken:
### xxl-job executor appname
xxl.job.executor.appname: rccp-management
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
xxl.job.executor.address:
### xxl-job executor server-info
xxl.job.executor.ip:
xxl.job.executor.port: 9998
### xxl-job executor log-path
xxl.job.executor.logpath: ./jobhandler
### xxl-job executor log-retention-days
xxl.job.executor.logretentiondays: 30

sftp.host: 47.94.168.49
sftp.username: root
sftp.port: 8089
sftp.path: ../usr/local/nginx/html/downloadapp/guanwang/
sftp.password: %TpGm*#Ne1E*zhongzhu11@#$78
sftp.show.path: /downloadapp/guanwang/
