server:
  port: 8804
  tomcat:
    max-http-post-size: 0
    max-http-header-size: 104857600
    uri-encoding: UTF-8


eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}



spring:
  datasource:
    driverClassName: ${rccp.micro.datasource.driverClassName}
    druid:
      main-db:
        url: ${rccp.micro.datasource.url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
      user-db:
        url: ${rccp.micro.datasource.user_url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
      search-db:
        url: ${rccp.micro.datasource.search_url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://${eureka.instance.hostname}:8767/

  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: ${rccp.micro.stream.kafka.binder.brokers}
          zk-nodes: ${rccp.micro.stream.kafka.binder.zk-nodes}
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  eureka:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

debug: true
logging:
  level:
    com.zhuj.micro.user.service.**.*: debug



#通过密码模式获取token地址
TOKEN_PWD_URL: http://${eureka.instance.hostname}:8763/api-oauth/oauth/token?grant_type=password


#微信支付参数
WXAPP_ID: wx540b5c4e9bfe69a3
APP_SECRET: 5fab8e3042389a7c6cd6b01bb544dd5e
WXMCH_ID: 1603301245
WXAPI_KEY: y9KqdOsPnIGKAevsSEb45uOPfqQjJi1R
NOTIFY_URL: http://192.168.1.71:8763/api-user/wxRenotify/payCallBack
UFDODER_URL: https://api.mch.weixin.qq.com/pay/unifiedorder
CHECK_URL: https://api.mch.weixin.qq.com/pay/orderquery
REFUND_URL: https://api.mch.weixin.qq.com/secapi/pay/refund
CASHOUT_URL: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
REFUND_NOTIFY_URL: http://192.168.1.71:8763/api-user/wxRenotify/refundCallBack
WX_CERT_URL: https://content.zhujianyun.com/wxCertificate/apiclient_cert.p12
REFUND_ORDER_URL: https://api.mch.weixin.qq.com/pay/refundquery
TRADE_TYPE: NATIVE
SIGN_TYP: MD5


#支付宝支付参数
ALAPP_ID: 2021001163629730
#支付宝应用私钥
ALAPP_PRIVATE_ID: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCGryG50CGbUuRcKppZTCorsUiZSyU0meX6pEiD5JJXQXgWMi1qvUNfUnBBuxnqsScqXkmlIoHSVTgQd7bvvL2uu/UONFWU5SbhZ1+3mejFuduBW67TMCdhNaJABFilL05ew6nxCew0n37fPbTYfisoDOCjlRQCo8C7Tr4okd0uZiM3DNqdjnyLi3KmHHlS12wfXhhWDwRPS2dTotyfN/4NurvoALuAEm/dMaFhgF1etZ7ShEGF5AtWwKHP+cqv/xYtH1PYSW9PFDseyk/8gdKs0Rx+/olaEYHIpljv0qtFU/VCPzlAVT9xmNZzt8jnihHOwEqwFtHd53XMcai0dEaVAgMBAAECggEAb9okHSe/sTn/EpgDBWQepZie3UguBuhEuYoT+w0ph7OEYpKba0jxGcniFoSnOmSTTTlu2ei1fhNt8yco0yKhOOs50ekepgBE8O8j69uzF/qJVH3qy9Ly8WVUcOvrHowR/ttqWBbQhsdq20Vo2l61wpYnPVNCggqythvoCtNQqAXKJ2Ni2yfhzYiTtru8URuaZQxLW1qvGM9Yo8Onimxt7D7dvy1JFR7LDkL/ZZzyIv+JBnH+l32kzZi8rFH8OoXQlPVtIIpe/8hNv9aoZOcM3YNZe+fXuFhos/zqUE9uKO5xn4KoHtXrPEH9HxdHBO0uYgXfvyZQwzEj65q+i6MS4QKBgQDjlmxK7kcjHVXZf+DqiErLJDudz6f5Sh1ehPn0HnBBAhJhSsSPs4XYGt0tu6mBfDwdCq7ThPTynAPa9Vm3ZX6qRRII7Wfj1l1JsBJU5ti+uMyu6KOKBrz5tkAl1cTLElsbSAHPx438SFBuRcMuWO9RQMXpPhPQSP5Q7eV7EVyGmQKBgQCXf5A77kZJWhEmN3lHChEAzHGrm7H98SoFKVfC3DU7EIRzqkODGYOQ3QqErmJPlmanr8P76+hy+HgMGXAl+Juj9HqJbrlNrPSb2wB4hVlMJgY/lKpURBhE+oVmyu6syG3eUa/bEwMg9zP/GOCDrZOQTf1h8Z5jZ1fcPQPka3wJXQKBgEyhkrcsQjG1p/mDUIVH/P8npRc/G40aAoeX+N3U/fE1tGCkH0lPpmqcqQrEHJAn98nDlhhMtXmXRMkOQfY5q4vDlA4Dei7COEkeix2hWSvm56yhUqegGzNtxW236/qApMKr3UhMJifjZYmr3cuWUIaoa7tclqlUWqV/ZPyqXOBJAoGAA09uP2D9eCzXoxYjOEIoDPRqp21Hflz+pg45NLDLGPdLbZuSzhKIpWmvCScmTsbih1d32NFWyuxS8zC7GplMDVESPF6G/gOBdMZcREXlpZxPFqSQ9DZosVkoAQ7+GBhpDiqKxSatMtMz96b7gOUSDF0n5DP7WgCwEsfiheMzWqECgYBXrnAFKsA8EwCtnv9rnCVFV0Zdga7e+5srXBGSbdpUwuqLLu9H5cPHo1CY/KMzj4Z2ZEdwT3cyll0EhlbrsY+ImhJNAf22NlDGGDS+OjSa/YhnW8db5V7lJoGzS9K117XvRB6SWGff5fa4zyokm8x90ssfzhkSuGYTHzxDzgxeRQ==
#支付宝应用公钥证书 开发71服务器
APP_PUBLIC_CERT_PATH: /home/zhujianyun/resources/appCertPublicKey_2021001189642509.crt
#支付宝公钥证书 开发71服务器
ALPUBLIC_CERT_PATH: /home/zhujianyun/resources/alipayCertPublicKey_RSA2.crt
#支付宝根证书 开发71服务器
ALROOTCERT_PATH: /home/zhujianyun/resources/alipayRootCert.crt
ALNOTIFY_URL: http://192.168.1.71:8763/api-user/alRenotify/NotifyURL
ALRETURN_URL: http://192.168.1.71:8763/api-user/alRenotify/ReturnURL
ALSIGN_TYPE: RSA2
ALCHARSET: utf-8
ALGETEWAY_URL: https://openapi.alipay.com/gateway.do
AL_CALL_BACK: http://192.168.1.70/zhujianyunDev/#/PersonMeg

#IAP ios内购
CERTIFICATEURL: https://buy.itunes.apple.com/verifyReceipt
CERTIFICATEURLTEST: https://sandbox.itunes.apple.com/verifyReceipt

DEFAULT: 0
ONE: 1
TWO: 2
THREE: 3
FOUR: 4
FIVE: 5

DEFAULT_MONEY: 0
ONELEVEL: 10
TWOLEVEl: 100
THREELEVEL: 500
FOURLEVEL: 2000

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

rate: 0.5

#云豆提现装换
withdrawalRate: 100
#云豆提现装换
andCloudBeans: 0.01
#余额提现
balanceTaxRate: 0.008
